### PR TITLE
Fix cover service listen port issue for #74

### LINKED ISSUE #74: Covered service may still use the previous listened address even compiled with `goc build --agentport xxx` if xx_profile_listen_addr file existed
From: https://testerhome.com/topics/24515
Problems probably in: https://github.com/qiniu/goc/blob/master/pkg/cover/instrument.go#L254

we need adjust the logic。

### PR DESCRIPTION
**Pull request by memoryliu**
Fix #74

### CODE REVIEW

File: pkg/cover/instrument.go [hunk 1]
```diff
@@ -252,26 +252,37 @@ func isNetworkError(err error) bool {
...
-	}
 	agentPort := "{{.AgentPort }}"
 	if agentPort != "" {
-		ln, err = net.Listen("tcp4", agentPort)
+		if ln, err = net.Listen("tcp4", agentPort); err != nil {
+			return
+		}
+		if host, err = getRealHost(ln); err != nil {
+			return
+		}
```
Comment (CarlJi) [inline pkg/cover/instrument.go:262]: it would be better to overwrite the address in the local temp persistent file
